// Mock data for demonstration
export const mockUsers = [
  {
    id: 'user1',
    name: 'John Admin',
    email: 'admin@fleet.com',
    role: 'admin',
    status: 'active',
  },
  {
    id: 'user2',
    name: 'Mike Driver',
    email: 'driver@fleet.com',
    role: 'driver',
    status: 'active',
  },
];

export const mockVehicles = [
  {
    id: 'vehicle1',
    name: 'Truck A',
    plate: 'ABC-123',
    driver_id: 'user2',
    driver_email: 'driver@fleet.com',
    driver_name: 'Mike Driver',
    status: 'available',
    latitude: 40.7128,
    longitude: -74.006,
    speed: 0,
    battery: 95,
    fuel: 85,
    odometer: 45230,
    model: 'Volvo FH16',
    year: 2022,
    color: 'Red',
    created_date: new Date().toISOString(),
    updated_date: new Date().toISOString(),
  },
  {
    id: 'vehicle2',
    name: 'Van B',
    plate: 'XYZ-789',
    driver_id: 'user2',
    driver_email: 'driver@fleet.com',
    driver_name: 'Mike Driver',
    status: 'on_trip',
    current_trip_id: 'trip1',
    current_destination: 'Airport Terminal',
    latitude: 40.758,
    longitude: -73.9855,
    speed: 45,
    battery: 78,
    fuel: 60,
    odometer: 32150,
    model: 'Mercedes Sprinter',
    year: 2023,
    color: 'White',
    created_date: new Date().toISOString(),
    updated_date: new Date().toISOString(),
  },
  {
    id: 'vehicle3',
    name: 'Bus C',
    plate: 'DEF-456',
    driver_id: 'user2',
    driver_email: 'driver@fleet.com',
    driver_name: 'Mike Driver',
    status: 'offline',
    latitude: 40.6892,
    longitude: -74.0445,
    speed: 0,
    battery: 30,
    fuel: 40,
    odometer: 78900,
    model: 'Isuzu Citibus',
    year: 2020,
    color: 'Blue',
    created_date: new Date().toISOString(),
    updated_date: new Date().toISOString(),
  },
];

export const mockTrips = [
  {
    id: 'trip1',
    vehicle_id: 'vehicle1',
    vehicle_name: 'Truck A',
    driver_id: 'user2',
    driver_email: 'driver@fleet.com',
    driver_name: 'Mike Driver',
    destination: 'Airport Terminal',
    start_location: 'Downtown Hub',
    end_location: 'Airport Terminal',
    status: 'active',
    start_time: new Date(Date.now() - 3600000).toISOString(),
    end_time: null,
    distance: 15.2,
    distance_km: 15.2,
    duration: 1800,
    average_speed: 50,
    max_speed: 65,
    start_lat: 40.7128,
    start_lng: -74.006,
    end_lat: 40.7761,
    end_lng: -73.8727,
    cost: 0,
    notes: 'Regular delivery',
    created_date: new Date(Date.now() - 3600000).toISOString(),
    updated_date: new Date().toISOString(),
  },
  {
    id: 'trip2',
    vehicle_id: 'vehicle2',
    vehicle_name: 'Van B',
    driver_id: 'user2',
    driver_email: 'driver@fleet.com',
    driver_name: 'Mike Driver',
    destination: 'Central Station',
    start_location: 'Port Authority',
    end_location: 'Central Station',
    status: 'completed',
    start_time: new Date(Date.now() - 7200000).toISOString(),
    end_time: new Date(Date.now() - 3600000).toISOString(),
    distance: 8.5,
    distance_km: 8.5,
    duration: 1200,
    average_speed: 42,
    max_speed: 55,
    start_lat: 40.7565,
    start_lng: -73.9906,
    end_lat: 40.7525,
    end_lng: -73.9777,
    cost: 25.50,
    notes: 'Completed on time',
    created_date: new Date(Date.now() - 7200000).toISOString(),
    updated_date: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const mockLocationLogs = [
  {
    id: 'log1',
    trip_id: 'trip1',
    vehicle_id: 'vehicle1',
    latitude: 40.7128,
    longitude: -74.006,
    speed: 0,
    altitude: 10,
    accuracy: 5,
    heading: 45,
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'log2',
    trip_id: 'trip1',
    vehicle_id: 'vehicle1',
    latitude: 40.7200,
    longitude: -73.9950,
    speed: 35,
    altitude: 15,
    accuracy: 5,
    heading: 45,
    timestamp: new Date(Date.now() - 3300000).toISOString(),
  },
  {
    id: 'log3',
    trip_id: 'trip1',
    vehicle_id: 'vehicle1',
    latitude: 40.7350,
    longitude: -73.9750,
    speed: 50,
    altitude: 20,
    accuracy: 5,
    heading: 45,
    timestamp: new Date(Date.now() - 3000000).toISOString(),
  },
  {
    id: 'log4',
    trip_id: 'trip1',
    vehicle_id: 'vehicle1',
    latitude: 40.7450,
    longitude: -73.9600,
    speed: 55,
    altitude: 25,
    accuracy: 5,
    heading: 45,
    timestamp: new Date(Date.now() - 2700000).toISOString(),
  },
  {
    id: 'log5',
    trip_id: 'trip2',
    vehicle_id: 'vehicle2',
    latitude: 40.7565,
    longitude: -73.9906,
    speed: 20,
    timestamp: new Date(Date.now() - 7000000).toISOString(),
  },
  {
    id: 'log5b',
    trip_id: 'trip2',
    vehicle_id: 'vehicle2',
    latitude: 40.7550,
    longitude: -73.9880,
    speed: 28,
    timestamp: new Date(Date.now() - 6600000).toISOString(),
  },
  {
    id: 'log5c',
    trip_id: 'trip2',
    vehicle_id: 'vehicle2',
    latitude: 40.7540,
    longitude: -73.9850,
    speed: 35,
    timestamp: new Date(Date.now() - 6200000).toISOString(),
  },
  {
    id: 'log5d',
    trip_id: 'trip2',
    vehicle_id: 'vehicle2',
    latitude: 40.7535,
    longitude: -73.9820,
    speed: 40,
    timestamp: new Date(Date.now() - 5800000).toISOString(),
  },
  {
    id: 'log5e',
    trip_id: 'trip2',
    vehicle_id: 'vehicle2',
    latitude: 40.7530,
    longitude: -73.9800,
    speed: 38,
    timestamp: new Date(Date.now() - 5400000).toISOString(),
  },
  {
    id: 'log6',
    trip_id: 'trip2',
    vehicle_id: 'vehicle2',
    latitude: 40.7525,
    longitude: -73.9777,
    speed: 25,
    timestamp: new Date(Date.now() - 3800000).toISOString(),
  },
  {
    id: 'log6b',
    trip_id: 'trip1',
    vehicle_id: 'vehicle1',
    latitude: 40.7580,
    longitude: -73.9500,
    speed: 48,
    timestamp: new Date(Date.now() - 2400000).toISOString(),
  },
  {
    id: 'log6c',
    trip_id: 'trip1',
    vehicle_id: 'vehicle1',
    latitude: 40.7680,
    longitude: -73.9200,
    speed: 52,
    timestamp: new Date(Date.now() - 2100000).toISOString(),
  },
  {
    id: 'log6d',
    trip_id: 'trip1',
    vehicle_id: 'vehicle1',
    latitude: 40.7761,
    longitude: -73.8727,
    speed: 40,
    timestamp: new Date(Date.now() - 1800000).toISOString(),
  },
];

export const mockGeofences = [
  {
    id: 'geofence1',
    name: 'Downtown Zone',
    description: 'Manhattan downtown area',
    center_latitude: 40.7128,
    center_longitude: -74.006,
    radius_meters: 5000,
    alert_on_exit: true,
    alert_on_enter: false,
    is_active: true,
    created_date: new Date().toISOString(),
    updated_date: new Date().toISOString(),
  },
  {
    id: 'geofence2',
    name: 'Airport Zone',
    description: 'JFK Airport area',
    center_latitude: 40.6413,
    center_longitude: -73.7781,
    radius_meters: 10000,
    alert_on_exit: true,
    alert_on_enter: true,
    is_active: true,
    created_date: new Date().toISOString(),
    updated_date: new Date().toISOString(),
  },
];

export const mockMaintenance = [
  {
    id: 'maint1',
    vehicle_id: 'vehicle1',
    service_type: 'oil_change',
    description: 'Regular oil change',
    scheduled_date: new Date(Date.now() + 86400000 * 30).toISOString(),
    completed_date: null,
    status: 'pending',
    cost: 150,
    notes: 'Next service due in 30 days',
    created_date: new Date().toISOString(),
    updated_date: new Date().toISOString(),
  },
  {
    id: 'maint2',
    vehicle_id: 'vehicle2',
    service_type: 'tire_rotation',
    description: 'Tire rotation and balance',
    scheduled_date: new Date(Date.now() - 86400000 * 5).toISOString(),
    completed_date: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'completed',
    cost: 200,
    notes: 'All tires in good condition',
    created_date: new Date().toISOString(),
    updated_date: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const mockReportSchedules = [
  {
    id: 'report1',
    name: 'Weekly Fleet Summary',
    recipient_email: 'admin@fleet.com',
    day_of_week: 1,
    schedule: 'weekly',
    recipients: ['admin@fleet.com'],
    last_sent: new Date(Date.now() - 86400000 * 7).toISOString(),
    is_active: true,
    created_date: new Date().toISOString(),
    updated_date: new Date().toISOString(),
  },
];

// In-memory storage (resets on page reload)
let storageData = {
  vehicles: JSON.parse(JSON.stringify(mockVehicles)),
  trips: JSON.parse(JSON.stringify(mockTrips)),
  locationLogs: JSON.parse(JSON.stringify(mockLocationLogs)),
  geofences: JSON.parse(JSON.stringify(mockGeofences)),
  maintenance: JSON.parse(JSON.stringify(mockMaintenance)),
  reportSchedules: JSON.parse(JSON.stringify(mockReportSchedules)),
};

export const getStorageData = () => storageData;

export const resetStorageData = () => {
  storageData = {
    vehicles: JSON.parse(JSON.stringify(mockVehicles)),
    trips: JSON.parse(JSON.stringify(mockTrips)),
    locationLogs: JSON.parse(JSON.stringify(mockLocationLogs)),
    geofences: JSON.parse(JSON.stringify(mockGeofences)),
    maintenance: JSON.parse(JSON.stringify(mockMaintenance)),
    reportSchedules: JSON.parse(JSON.stringify(mockReportSchedules)),
  };
};
