// Hyderabad fleet demo data — realistic routes, TS registrations, Indian drivers

const now = Date.now();
const hours = (h) => new Date(now - h * 3600000).toISOString();
const days = (d) => new Date(now - d * 86400000).toISOString();

/** Interpolate GPS points between two coordinates */
function buildRoutePoints(tripId, vehicleId, start, end, pointCount, startTimeMs, intervalMin = 4) {
  const logs = [];
  for (let i = 0; i <= pointCount; i++) {
    const t = i / pointCount;
    logs.push({
      id: `log_${tripId}_${i}`,
      trip_id: tripId,
      vehicle_id: vehicleId,
      latitude: start.lat + (end.lat - start.lat) * t,
      longitude: start.lng + (end.lng - start.lng) * t,
      speed: 25 + Math.sin(t * Math.PI) * 30 + Math.random() * 8,
      heading: 90,
      accuracy: 4,
      timestamp: new Date(startTimeMs + i * intervalMin * 60000).toISOString(),
    });
  }
  return logs;
}

const HY = {
  hitech: { lat: 17.4435, lng: 78.3772, name: "Hitech City" },
  gachibowli: { lat: 17.4401, lng: 78.3489, name: "Gachibowli" },
  secunderabad: { lat: 17.4399, lng: 78.4983, name: "Secunderabad" },
  lbnagar: { lat: 17.366, lng: 78.557, name: "LB Nagar" },
  airport: { lat: 17.2403, lng: 78.4294, name: "RGIA Airport" },
  banjara: { lat: 17.4156, lng: 78.4347, name: "Banjara Hills" },
  miyapur: { lat: 17.4964, lng: 78.357, name: "Miyapur" },
  kukatpally: { lat: 17.4849, lng: 78.4138, name: "Kukatpally" },
  madhapur: { lat: 17.4483, lng: 78.3915, name: "Madhapur" },
  uppal: { lat: 17.4015, lng: 78.5582, name: "Uppal" },
};

export const mockUsers = [
  { id: "user1", name: "Arjun Mehta", email: "admin@fleet.com", role: "admin", status: "active" },
  { id: "user2", name: "Rajesh Kumar", email: "driver@fleet.com", role: "driver", status: "active" },
  { id: "user3", name: "Priya Reddy", email: "priya@fleet.com", role: "driver", status: "active" },
  { id: "user4", name: "Suresh Naik", email: "suresh@fleet.com", role: "driver", status: "active" },
];

export const mockVehicles = [
  {
    id: "v1",
    name: "Tata Ace HT",
    vehicle_name: "Tata Ace HT",
    plate: "TS09GA2847",
    vehicle_unique_id: "TS09GA2847",
    driver_id: "user2",
    driver_email: "driver@fleet.com",
    driver_name: "Rajesh Kumar",
    status: "on_trip",
    current_trip_id: "trip_active_1",
    current_destination: HY.airport.name,
    latitude: 17.38,
    longitude: 78.42,
    current_latitude: 17.38,
    current_longitude: 78.42,
    current_speed: 52,
    speed: 52,
    odometer_baseline_km: 28450,
    lifetime_distance_km: 31280,
    battery: 88,
    fuel: 72,
    model: "Tata Ace HT",
    year: 2022,
    last_location_update: hours(0.01),
    created_date: days(120),
    updated_date: hours(0.01),
  },
  {
    id: "v2",
    name: "Mahindra Bolero",
    vehicle_name: "Mahindra Bolero",
    plate: "TS07UK5521",
    vehicle_unique_id: "TS07UK5521",
    driver_id: "user3",
    driver_email: "priya@fleet.com",
    driver_name: "Priya Reddy",
    status: "available",
    latitude: HY.gachibowli.lat,
    longitude: HY.gachibowli.lng,
    current_latitude: HY.gachibowli.lat,
    current_longitude: HY.gachibowli.lng,
    current_speed: 0,
    speed: 0,
    odometer_baseline_km: 42100,
    lifetime_distance_km: 44820,
    battery: 91,
    fuel: 65,
    model: "Mahindra Bolero Pik-Up",
    year: 2021,
    last_location_update: hours(0.05),
    created_date: days(200),
    updated_date: hours(0.05),
  },
  {
    id: "v3",
    name: "Eicher Pro 2049",
    vehicle_name: "Eicher Pro 2049",
    plate: "TS08EN9012",
    vehicle_unique_id: "TS08EN9012",
    driver_id: "user4",
    driver_email: "suresh@fleet.com",
    driver_name: "Suresh Naik",
    status: "maintenance",
    latitude: HY.kukatpally.lat,
    longitude: HY.kukatpally.lng,
    current_latitude: HY.kukatpally.lat,
    current_longitude: HY.kukatpally.lng,
    current_speed: 0,
    speed: 0,
    odometer_baseline_km: 67800,
    lifetime_distance_km: 68120,
    battery: 45,
    fuel: 30,
    model: "Eicher Pro 2049",
    year: 2020,
    last_location_update: hours(2),
    created_date: days(300),
    updated_date: hours(2),
  },
  {
    id: "v4",
    name: "Ashok Leyland Dost",
    vehicle_name: "Ashok Leyland Dost",
    plate: "TS10HT3340",
    vehicle_unique_id: "TS10HT3340",
    driver_id: "user2",
    driver_email: "driver@fleet.com",
    driver_name: "Rajesh Kumar",
    status: "offline",
    latitude: HY.lbnagar.lat,
    longitude: HY.lbnagar.lng,
    current_latitude: HY.lbnagar.lat,
    current_longitude: HY.lbnagar.lng,
    current_speed: 0,
    speed: 0,
    odometer_baseline_km: 19200,
    lifetime_distance_km: 21450,
    battery: 12,
    fuel: 20,
    model: "Ashok Leyland Dost+",
    year: 2019,
    last_location_update: days(1),
    created_date: days(400),
    updated_date: days(1),
  },
  {
    id: "v5",
    name: "Force Traveller",
    vehicle_name: "Force Traveller",
    plate: "TS09AB7723",
    vehicle_unique_id: "TS09AB7723",
    driver_id: "user3",
    driver_email: "priya@fleet.com",
    driver_name: "Priya Reddy",
    status: "on_trip",
    current_trip_id: "trip_active_2",
    current_destination: HY.secunderabad.name,
    latitude: 17.43,
    longitude: 78.47,
    current_latitude: 17.43,
    current_longitude: 78.47,
    current_speed: 38,
    speed: 38,
    odometer_baseline_km: 35600,
    lifetime_distance_km: 38940,
    battery: 76,
    fuel: 58,
    model: "Force Traveller 3050",
    year: 2023,
    last_location_update: hours(0.02),
    created_date: days(90),
    updated_date: hours(0.02),
  },
  {
    id: "v6",
    name: "Maruti Super Carry",
    vehicle_name: "Maruti Super Carry",
    plate: "TS11EK4456",
    vehicle_unique_id: "TS11EK4456",
    driver_id: "user4",
    driver_email: "suresh@fleet.com",
    driver_name: "Suresh Naik",
    status: "available",
    latitude: HY.miyapur.lat,
    longitude: HY.miyapur.lng,
    current_latitude: HY.miyapur.lat,
    current_longitude: HY.miyapur.lng,
    current_speed: 0,
    speed: 0,
    odometer_baseline_km: 12800,
    lifetime_distance_km: 14120,
    battery: 94,
    fuel: 80,
    model: "Maruti Super Carry",
    year: 2024,
    last_location_update: hours(0.08),
    created_date: days(60),
    updated_date: hours(0.08),
  },
];

export const mockTrips = [
  {
    id: "trip_active_1",
    vehicle_id: "v1",
    vehicle_name: "Tata Ace HT",
    driver_email: "driver@fleet.com",
    driver_name: "Rajesh Kumar",
    start_location: HY.madhapur.name,
    destination: HY.airport.name,
    end_location: null,
    status: "active",
    start_time: hours(1.2),
    end_time: null,
    distance_km: 18.4,
    distance: 18.4,
    start_lat: HY.madhapur.lat,
    start_lng: HY.madhapur.lng,
    end_lat: HY.airport.lat,
    end_lng: HY.airport.lng,
    created_date: hours(1.2),
    updated_date: hours(0.01),
  },
  {
    id: "trip_active_2",
    vehicle_id: "v5",
    vehicle_name: "Force Traveller",
    driver_email: "priya@fleet.com",
    driver_name: "Priya Reddy",
    start_location: HY.banjara.name,
    destination: HY.secunderabad.name,
    end_location: null,
    status: "active",
    start_time: hours(0.8),
    end_time: null,
    distance_km: 9.2,
    distance: 9.2,
    start_lat: HY.banjara.lat,
    start_lng: HY.banjara.lng,
    end_lat: HY.secunderabad.lat,
    end_lng: HY.secunderabad.lng,
    created_date: hours(0.8),
    updated_date: hours(0.02),
  },
  {
    id: "trip_c1",
    vehicle_id: "v2",
    vehicle_name: "Mahindra Bolero",
    driver_email: "priya@fleet.com",
    driver_name: "Priya Reddy",
    start_location: HY.hitech.name,
    destination: HY.gachibowli.name,
    end_location: HY.gachibowli.name,
    status: "completed",
    start_time: hours(26),
    end_time: hours(24),
    distance_km: 12.6,
    distance: 12.6,
    start_lat: HY.hitech.lat,
    start_lng: HY.hitech.lng,
    end_lat: HY.gachibowli.lat,
    end_lng: HY.gachibowli.lng,
    created_date: hours(26),
    updated_date: hours(24),
  },
  {
    id: "trip_c2",
    vehicle_id: "v1",
    vehicle_name: "Tata Ace HT",
    driver_email: "driver@fleet.com",
    driver_name: "Rajesh Kumar",
    start_location: HY.kukatpally.name,
    destination: HY.uppal.name,
    end_location: HY.uppal.name,
    status: "completed",
    start_time: hours(50),
    end_time: hours(47),
    distance_km: 22.1,
    distance: 22.1,
    start_lat: HY.kukatpally.lat,
    start_lng: HY.kukatpally.lng,
    end_lat: HY.uppal.lat,
    end_lng: HY.uppal.lng,
    created_date: hours(50),
    updated_date: hours(47),
  },
  {
    id: "trip_c3",
    vehicle_id: "v5",
    vehicle_name: "Force Traveller",
    driver_email: "priya@fleet.com",
    driver_name: "Priya Reddy",
    start_location: HY.secunderabad.name,
    destination: HY.lbnagar.name,
    end_location: HY.lbnagar.name,
    status: "completed",
    start_time: days(2),
    end_time: days(2),
    distance_km: 16.8,
    distance: 16.8,
    start_lat: HY.secunderabad.lat,
    start_lng: HY.secunderabad.lng,
    end_lat: HY.lbnagar.lat,
    end_lng: HY.lbnagar.lng,
    created_date: days(2),
    updated_date: days(2),
  },
  {
    id: "trip_c4",
    vehicle_id: "v6",
    vehicle_name: "Maruti Super Carry",
    driver_email: "suresh@fleet.com",
    driver_name: "Suresh Naik",
    start_location: HY.miyapur.name,
    destination: HY.hitech.name,
    end_location: HY.hitech.name,
    status: "completed",
    start_time: days(3),
    end_time: days(3),
    distance_km: 14.3,
    distance: 14.3,
    start_lat: HY.miyapur.lat,
    start_lng: HY.miyapur.lng,
    end_lat: HY.hitech.lat,
    end_lng: HY.hitech.lng,
    created_date: days(3),
    updated_date: days(3),
  },
  {
    id: "trip_c5",
    vehicle_id: "v2",
    vehicle_name: "Mahindra Bolero",
    driver_email: "priya@fleet.com",
    driver_name: "Priya Reddy",
    start_location: HY.banjara.name,
    destination: HY.airport.name,
    end_location: HY.airport.name,
    status: "completed",
    start_time: days(5),
    end_time: days(5),
    distance_km: 31.5,
    distance: 31.5,
    start_lat: HY.banjara.lat,
    start_lng: HY.banjara.lng,
    end_lat: HY.airport.lat,
    end_lng: HY.airport.lng,
    created_date: days(5),
    updated_date: days(5),
  },
  {
    id: "trip_cancel_1",
    vehicle_id: "v4",
    vehicle_name: "Ashok Leyland Dost",
    driver_email: "driver@fleet.com",
    driver_name: "Rajesh Kumar",
    start_location: HY.lbnagar.name,
    destination: HY.gachibowli.name,
    end_location: null,
    status: "cancelled",
    start_time: days(4),
    end_time: days(4),
    distance_km: 3.2,
    distance: 3.2,
    start_lat: HY.lbnagar.lat,
    start_lng: HY.lbnagar.lng,
    created_date: days(4),
    updated_date: days(4),
  },
];

const trip1Start = now - 1.2 * 3600000;
const trip2Start = now - 0.8 * 3600000;

export const mockLocationLogs = [
  ...buildRoutePoints("trip_active_1", "v1", HY.madhapur, { lat: 17.38, lng: 78.42 }, 14, trip1Start, 5),
  ...buildRoutePoints("trip_active_2", "v5", HY.banjara, HY.secunderabad, 10, trip2Start, 4),
  ...buildRoutePoints("trip_c1", "v2", HY.hitech, HY.gachibowli, 8, now - 26 * 3600000, 5),
  ...buildRoutePoints("trip_c2", "v1", HY.kukatpally, HY.uppal, 12, now - 50 * 3600000, 6),
  ...buildRoutePoints("trip_c3", "v5", HY.secunderabad, HY.lbnagar, 10, now - 2 * 86400000, 5),
  ...buildRoutePoints("trip_c4", "v6", HY.miyapur, HY.hitech, 9, now - 3 * 86400000, 5),
  ...buildRoutePoints("trip_c5", "v2", HY.banjara, HY.airport, 16, now - 5 * 86400000, 7),
];

export const mockGeofences = [
  {
    id: "geo1",
    name: "Hitech City Hub",
    description: "IT corridor depot",
    center_latitude: HY.hitech.lat,
    center_longitude: HY.hitech.lng,
    radius_meters: 2500,
    alert_on_exit: true,
    alert_on_enter: false,
    is_active: true,
    created_date: days(30),
    updated_date: days(1),
  },
  {
    id: "geo2",
    name: "RGIA Airport Zone",
    description: "Cargo pickup zone",
    center_latitude: HY.airport.lat,
    center_longitude: HY.airport.lng,
    radius_meters: 4000,
    alert_on_exit: true,
    alert_on_enter: true,
    is_active: true,
    created_date: days(30),
    updated_date: days(1),
  },
  {
    id: "geo3",
    name: "Secunderabad WH",
    description: "Warehouse perimeter",
    center_latitude: HY.secunderabad.lat,
    center_longitude: HY.secunderabad.lng,
    radius_meters: 1800,
    alert_on_exit: true,
    alert_on_enter: true,
    is_active: true,
    created_date: days(20),
    updated_date: days(2),
  },
];

export const mockMaintenance = [
  {
    id: "maint1",
    vehicle_id: "v3",
    service_type: "brake_service",
    description: "Brake pad replacement — Eicher Pro",
    scheduled_date: days(-1),
    completed_date: null,
    status: "in_progress",
    cost: 8500,
    notes: "At Kukatpally service centre",
    created_date: days(3),
    updated_date: hours(2),
  },
];

export const mockReportSchedules = [
  {
    id: "report1",
    name: "Weekly Hyderabad Fleet Summary",
    recipient_email: "admin@fleet.com",
    day_of_week: 1,
    schedule: "weekly",
    recipients: ["admin@fleet.com"],
    last_sent: days(7),
    is_active: true,
    created_date: days(60),
    updated_date: days(1),
  },
];

let storageData = {
  vehicles: JSON.parse(JSON.stringify(mockVehicles)),
  trips: JSON.parse(JSON.stringify(mockTrips)),
  locationLogs: JSON.parse(JSON.stringify(mockLocationLogs)),
  geofences: JSON.parse(JSON.stringify(mockGeofences)),
  maintenance: JSON.parse(JSON.stringify(mockMaintenance)),
  reportSchedules: JSON.parse(JSON.stringify(mockReportSchedules)),
};

export const getStorageData = () => storageData;

export const resetStorageData = () => {
  storageData = {
    vehicles: JSON.parse(JSON.stringify(mockVehicles)),
    trips: JSON.parse(JSON.stringify(mockTrips)),
    locationLogs: JSON.parse(JSON.stringify(mockLocationLogs)),
    geofences: JSON.parse(JSON.stringify(mockGeofences)),
    maintenance: JSON.parse(JSON.stringify(mockMaintenance)),
    reportSchedules: JSON.parse(JSON.stringify(mockReportSchedules)),
  };
};
