// generateTripReport function
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
import { jsPDF } from 'npm:jspdf@4.0.0';

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const user = await base44.auth.me();
  if (!user || user.role !== 'admin') {
    return Response.json({ error: 'Forbidden' }, { status: 403 });
  }

  const { trip_id } = await req.json();
  if (!trip_id) return Response.json({ error: 'trip_id required' }, { status: 400 });

  const trips = await base44.asServiceRole.entities.Trip.filter({ id: trip_id });
  const trip = trips[0];
  if (!trip) return Response.json({ error: 'Trip not found' }, { status: 404 });

  // Fetch location logs for this trip
  const logs = await base44.asServiceRole.entities.LocationLog.filter(
    { trip_id },
    'created_date',
    500
  );

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header bar
  doc.setFillColor(14, 165, 117);
  doc.rect(0, 0, pageWidth, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('FleetTrack - Trip Report', 14, 18);

  doc.setTextColor(60, 60, 60);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  // Trip summary section
  let y = 40;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Trip Summary', 14, y);
  y += 6;
  doc.setDrawColor(220, 220, 220);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  const formatDate = (dt) => dt ? new Date(dt).toLocaleString() : '—';
  const diffMin = (trip.start_time && trip.end_time)
    ? Math.round((new Date(trip.end_time) - new Date(trip.start_time)) / 60000)
    : null;
  const duration = diffMin !== null
    ? (diffMin >= 60 ? `${Math.floor(diffMin / 60)}h ${diffMin % 60}m` : `${diffMin}m`)
    : '—';

  const fields = [
    ['Vehicle', trip.vehicle_name || '—'],
    ['Driver', trip.driver_name || '—'],
    ['Driver Email', trip.driver_email || '—'],
    ['Destination', trip.destination || '—'],
    ['Status', trip.status || '—'],
    ['Start Time', formatDate(trip.start_time)],
    ['End Time', formatDate(trip.end_time)],
    ['Duration', duration],
    ['Distance', trip.distance_km != null ? `${trip.distance_km.toFixed(2)} km` : '—'],
  ];

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  fields.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label + ':', 14, y);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value), 70, y);
    y += 8;
  });

  // GPS Path summary
  if (logs.length > 0) {
    y += 4;
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('GPS Path Summary', 14, y);
    y += 6;
    doc.line(14, y, pageWidth - 14, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const first = logs[0];
    const last = logs[logs.length - 1];
    doc.text(`Total GPS Points Recorded: ${logs.length}`, 14, y); y += 7;
    doc.text(`Start Location: ${first.latitude?.toFixed(5)}, ${first.longitude?.toFixed(5)}`, 14, y); y += 7;
    doc.text(`End Location: ${last.latitude?.toFixed(5)}, ${last.longitude?.toFixed(5)}`, 14, y); y += 7;

    const speeds = logs.filter(l => l.speed != null).map(l => l.speed);
    if (speeds.length) {
      const avgSpeed = (speeds.reduce((a, b) => a + b, 0) / speeds.length).toFixed(1);
      const maxSpeed = Math.max(...speeds).toFixed(1);
      doc.text(`Average Speed: ${avgSpeed} km/h`, 14, y); y += 7;
      doc.text(`Max Speed: ${maxSpeed} km/h`, 14, y); y += 7;
    }

    // Log table (first 20 entries)
    y += 4;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Location Log (first 20 entries)', 14, y);
    y += 6;
    doc.line(14, y, pageWidth - 14, y);
    y += 6;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('#', 14, y);
    doc.text('Timestamp', 22, y);
    doc.text('Latitude', 80, y);
    doc.text('Longitude', 115, y);
    doc.text('Speed (km/h)', 150, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    logs.slice(0, 20).forEach((log, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(String(i + 1), 14, y);
      doc.text(log.timestamp ? new Date(log.timestamp).toLocaleTimeString() : '—', 22, y);
      doc.text(log.latitude?.toFixed(5) || '—', 80, y);
      doc.text(log.longitude?.toFixed(5) || '—', 115, y);
      doc.text(log.speed != null ? log.speed.toFixed(1) : '—', 150, y);
      y += 6;
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(
      `Generated by FleetTrack on ${new Date().toLocaleDateString()} · Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' }
    );
  }

  const pdfBytes = doc.output('arraybuffer');
  return new Response(pdfBytes, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="trip-report-${trip_id}.pdf"`,
    },
  });
});